### ISSUE TITLE
Squashed Desktop Chat

### ISSUE THREAD

**Issue by LollipopFt** [TriviaParty/Bugs#3]
The chat display on the desktop is squashed together, and is hardly readable.
![haiz](https://user-images.githubusercontent.com/62802897/81401112-2eb9b880-9161-11ea-8183-5aa96eb1abbd.png)

**Comment by Sven65** [comment]
OS, browser and screen resolution?

**Comment by LollipopFt** [comment]
Windows 10 Pro, OS: 18362.778
Browser: Microsoft Edge, Google Chrome (tried on both)
Screen Resolution: 2736 × 1824
